# Generated by Django 4.2.4 on 2023-08-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaNome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True)),
                ('preco', models.FloatField()),
                ('capa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('categoriaNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.categoria')),
                ('tamanho', models.ManyToManyField(related_name='tamanhos', to='momentoespecial.tamanho')),
            ],
        ),
    ]
