# Generated by Django 4.2.4 on 2023-08-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentoespecial', '0004_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dataFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='dataInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
